"""add depends_on to spend_requests

Revision ID: 1a98b9a23904
Revises: a976d7d0510b
Create Date: 2026-03-14 02:04:23.580817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a98b9a23904'
down_revision = 'a976d7d0510b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spend_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depends_on', sa.Integer(), nullable=True))

    with op.batch_alter_table('xp_claims', schema=None) as batch_op:
        batch_op.create_index('ix_xp_claims_char_period', ['character_name', 'play_period'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_claims', schema=None) as batch_op:
        batch_op.drop_index('ix_xp_claims_char_period')

    with op.batch_alter_table('spend_requests', schema=None) as batch_op:
        batch_op.drop_column('depends_on')

    # ### end Alembic commands ###
