"""add warnings to wiki sync events

Revision ID: 48c34da82c09
Revises: 8beb375fc044
Create Date: 2026-08-11 09:51:04.522362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c34da82c09'
down_revision = '8beb375fc044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_sync_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_sync_events', schema=None) as batch_op:
        batch_op.drop_column('warnings')

    # ### end Alembic commands ###
