"""Add entry_uid to app_log_entries for bot-log retry dedupe

Revision ID: b9c54e8c57d1
Revises: 854a221ba7a1
Create Date: 2026-09-01 19:23:24.238538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c54e8c57d1'
down_revision = '854a221ba7a1'
branch_labels = None
depends_on = None


def upgrade():
    # Guarded the same way as 48c34da82c09: two containers can run this
    # concurrently on a rapid double deploy, and the loser of that race would
    # otherwise fail on an "already exists" error rather than no-opping.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = {c['name'] for c in inspector.get_columns('app_log_entries')}
    if 'entry_uid' not in existing_cols:
        with op.batch_alter_table('app_log_entries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('entry_uid', sa.String(length=36), nullable=True))

    existing_indexes = {i['name'] for i in inspector.get_indexes('app_log_entries')}
    if 'ix_app_log_entries_entry_uid' not in existing_indexes:
        with op.batch_alter_table('app_log_entries', schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f('ix_app_log_entries_entry_uid'), ['entry_uid'], unique=False,
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_log_entries_entry_uid'))
        batch_op.drop_column('entry_uid')

    # ### end Alembic commands ###
