"""Character Creator admin routes.

Provides:
  GET  /api/cc/restrictions               — public; used by SPA to filter banned components
  GET  /cc-admin/drafts                   — staff UI: list submitted drafts
  GET  /cc-admin/drafts/<id>              — staff UI: review a single draft
  POST /cc-admin/drafts/<id>/approve      — staff: approve a draft
  POST /cc-admin/drafts/<id>/request-revision — staff: send draft back for revision
  GET  /cc-admin/loresheets               — staff UI: view/manage loresheet bans
  POST /cc-admin/loresheets/<id>/ban      — staff: ban a loresheet
  POST /cc-admin/loresheets/<id>/unban    — staff: lift a loresheet ban
"""

import json
import os
from datetime import datetime, timezone
from functools import lru_cache

from flask import Blueprint, abort, flash, jsonify, redirect, render_template, request, session, url_for

import logging

from app.auth import require_staff
from app.db import CharacterDraft, CcRestriction, DbCharacter, db
from app import db_service, sheets_sync
from app.models import Character

logger = logging.getLogger(__name__)

# Map CC clan name → default sect
_CLAN_SECT: dict[str, str] = {
    'brujah': 'Anarch', 'gangrel': 'Anarch', 'nosferatu': 'Anarch',
    'toreador': 'Camarilla', 'tremere': 'Camarilla', 'ventrue': 'Camarilla',
    'malkavian': 'Camarilla', 'caitiff': 'Anarch',
    'lasombra': 'Camarilla', 'ministry': 'Anarch', 'ravnos': 'Autarkis',
    'salubri': 'Autarkis', 'tzimisce': 'Autarkis', 'hecata': 'Hecata',
    'banu haqim': 'Camarilla', 'giovanni': 'Hecata',
    'thin-blood': 'Autarkis',
}

# loresheet-catalog.json is generated by the Vite build (loresheetCatalogPlugin)
# and copied into Flask's static directory by the Dockerfile.
_CATALOG_JSON = os.path.normpath(
    os.path.join(os.path.dirname(__file__), '..', 'static', 'character-app', 'loresheet-catalog.json')
)

_SOURCE_LABELS = {
    'core': 'V5 Core',
    'camarilla': 'Camarilla',
    'anarch': 'Anarch',
    'chicago': 'Chicago by Night',
    'players-guide': "Player's Guide",
    'gehenna-war': 'Gehenna War',
    'in-memoriam': 'In Memoriam',
    'tattered-facade': 'Tattered Facade',
    'blood-sigils': 'Blood Sigils',
    'cults-of-the-blood-gods': 'Cults of the Blood Gods',
    'chicago-folios': 'Chicago Folios',
    'children-of-the-blood': 'Children of the Blood',
    'book-of-nod-apocrypha': 'Book of Nod Apocrypha',
    'let-the-streets-run-red': 'Let the Streets Run Red',
    'fall-of-london': 'The Fall of London',
    'forbidden-religions': 'Forbidden Religions',
    'trails-of-ash-and-bone': 'Trails of Ash and Bone',
    'live-from-the-succubus-club': 'Live From the Succubus Club',
    'download': 'Download / Choice of Games',
    'winters-teeth': "Winter's Teeth",
    'custom': 'Nashville (Custom)',
}


@lru_cache(maxsize=1)
def _load_loresheet_catalog():
    """Load id/name/source from loresheet-catalog.json (generated at SPA build time)."""
    try:
        with open(_CATALOG_JSON, encoding='utf-8') as f:
            entries = json.load(f)
    except OSError:
        return []
    return [
        {**e, 'source_label': _SOURCE_LABELS.get(e.get('source', ''), e.get('source', ''))}
        for e in entries
        if 'id' in e and 'name' in e and 'source' in e
    ]

bp = Blueprint('cc_admin', __name__)

COMPONENT_TYPE_LORESHEET = 'loresheet'


# ---------------------------------------------------------------------------
# Public API — consumed by the character creator SPA
# ---------------------------------------------------------------------------

@bp.route('/api/cc/restrictions')
def cc_restrictions():
    """Return all active component bans, grouped by type.

    Response shape:
      { "loresheets": ["minneapolis", "the-nictuku", ...] }
    """
    rows = CcRestriction.query.filter_by(component_type=COMPONENT_TYPE_LORESHEET).all()
    return jsonify({'loresheets': [r.component_id for r in rows]})


# ---------------------------------------------------------------------------
# Staff admin UI — loresheet management
# ---------------------------------------------------------------------------

@bp.route('/cc-admin/loresheets')
@require_staff
def loresheet_list():
    """Staff view: all loresheets with ban status."""
    banned_rows = {
        r.component_id: r
        for r in CcRestriction.query.filter_by(component_type=COMPONENT_TYPE_LORESHEET).all()
    }
    catalog = _load_loresheet_catalog()
    return render_template(
        'cc_admin/loresheets.html',
        catalog=catalog,
        banned=banned_rows,
    )


@bp.route('/cc-admin/loresheets/<loresheet_id>/ban', methods=['POST'])
@require_staff
def loresheet_ban(loresheet_id):
    """Ban a loresheet."""
    reason = (request.form.get('reason') or '').strip()
    actor = session.get('staff_user') or session.get('discord_name') or 'unknown'

    existing = CcRestriction.query.filter_by(
        component_type=COMPONENT_TYPE_LORESHEET,
        component_id=loresheet_id,
    ).first()

    if existing:
        existing.reason = reason
        existing.updated_by = actor
        existing.updated_at = datetime.now(timezone.utc)
    else:
        db.session.add(CcRestriction(
            component_type=COMPONENT_TYPE_LORESHEET,
            component_id=loresheet_id,
            reason=reason,
            updated_by=actor,
            updated_at=datetime.now(timezone.utc),
        ))

    db.session.commit()
    flash(f'Loresheet "{loresheet_id}" banned.', 'success')
    return redirect(url_for('cc_admin.loresheet_list'))


@bp.route('/cc-admin/drafts')
@require_staff
def draft_list():
    """Staff view: all submitted, revision-requested, and approved character drafts."""
    status_filter = request.args.get('status', 'submitted')
    valid_statuses = ('submitted', 'revision_requested', 'approved', 'all')
    if status_filter not in valid_statuses:
        status_filter = 'submitted'

    q = CharacterDraft.query
    if status_filter != 'all':
        q = q.filter_by(status=status_filter)
    else:
        q = q.filter(CharacterDraft.status.in_(['submitted', 'revision_requested', 'approved']))
    drafts = q.order_by(CharacterDraft.submitted_at.desc()).all()

    counts = {
        s: CharacterDraft.query.filter_by(status=s).count()
        for s in ('submitted', 'revision_requested', 'approved')
    }
    drafts_with_data = [
        (d, json.loads(d.character_data) if d.character_data else {})
        for d in drafts
    ]
    return render_template(
        'cc_admin/drafts.html',
        drafts_with_data=drafts_with_data,
        status_filter=status_filter,
        counts=counts,
    )


@bp.route('/cc-admin/drafts/<draft_id>')
@require_staff
def draft_review(draft_id):
    """Staff view: review a single character draft."""
    draft = db.session.get(CharacterDraft, draft_id)
    if draft is None:
        abort(404)
    catalog_by_id = {e['id']: e for e in _load_loresheet_catalog()}
    char_data = json.loads(draft.character_data) if draft.character_data else {}
    return render_template(
        'cc_admin/draft_review.html',
        draft=draft,
        char_data=char_data,
        catalog_by_id=catalog_by_id,
    )


@bp.route('/cc-admin/drafts/<draft_id>/approve', methods=['POST'])
@require_staff
def draft_approve(draft_id):
    """Approve a character draft and create the roster entry if needed."""
    draft = db.session.get(CharacterDraft, draft_id)
    if draft is None:
        abort(404)
    actor = session.get('staff_user') or session.get('discord_name') or 'unknown'
    draft.status = 'approved'
    draft.approved_by = actor
    draft.approved_at = datetime.now(timezone.utc)

    # Create or link roster entry (DbCharacter)
    char_name = draft.character_name or ''
    if char_name and not draft.roster_character_id:
        existing_row = DbCharacter.query.filter(
            DbCharacter.character_name.ilike(char_name)
        ).first()
        if existing_row:
            draft.roster_character_id = existing_row.id
        else:
            char_data = {}
            if draft.character_data:
                try:
                    char_data = json.loads(draft.character_data)
                except Exception:
                    pass
            clan = (char_data.get('clan') or '').strip()
            age_cat = (char_data.get('age_category') or 'neonate').strip().capitalize()
            sect = _CLAN_SECT.get(clan.lower(), '')
            try:
                new_char = Character(
                    character_name=char_name,
                    player_discord=draft.player_discord_id or '',
                    clan=clan,
                    age_category=age_cat,
                    sect=sect,
                    active=True,
                    status='active',
                )
                db_service.add_character(new_char)
                if sheets_sync:
                    try:
                        sheets_sync.sync_add_character(new_char)
                    except Exception as sync_exc:
                        logger.warning('CC approval: sheets sync failed for %s: %s', char_name, sync_exc)
                new_row = DbCharacter.query.filter(
                    DbCharacter.character_name.ilike(char_name)
                ).first()
                if new_row:
                    draft.roster_character_id = new_row.id
                logger.info('CC approval: created roster entry for %s', char_name)
            except Exception as exc:
                logger.warning('CC approval: failed to create roster for %s: %s', char_name, exc)

    db.session.commit()
    flash(f'Character "{draft.character_name or draft.id}" approved.', 'success')
    return redirect(url_for('cc_admin.draft_list'))


@bp.route('/cc-admin/drafts/<draft_id>/request-revision', methods=['POST'])
@require_staff
def draft_request_revision(draft_id):
    """Send a character draft back to the player with revision notes."""
    draft = db.session.get(CharacterDraft, draft_id)
    if draft is None:
        abort(404)
    notes = (request.form.get('revision_notes') or '').strip()
    draft.status = 'revision_requested'
    draft.revision_notes = notes
    db.session.commit()
    flash(f'Revision requested for "{draft.character_name or draft.id}".', 'info')
    return redirect(url_for('cc_admin.draft_list'))


@bp.route('/cc-admin/drafts/<draft_id>/delete', methods=['POST'])
@require_staff
def draft_delete(draft_id):
    """Permanently delete a character draft and optionally its roster entry."""
    draft = db.session.get(CharacterDraft, draft_id)
    if draft is None:
        abort(404)

    char_name = draft.character_name or str(draft_id)
    also_delete_roster = request.form.get('delete_roster') == '1'

    if also_delete_roster and draft.roster_character_id:
        roster_row = db.session.get(DbCharacter, draft.roster_character_id)
        if roster_row:
            db.session.delete(roster_row)

    db.session.delete(draft)
    db.session.commit()

    actor = session.get('discord_name') or 'staff'
    db_service.log_action(
        staff_user=actor,
        action_type='draft_deleted',
        target=char_name,
        details=f'Draft {draft_id} deleted' + (' + roster entry' if also_delete_roster else ''),
    )
    flash(f'Draft for "{char_name}" deleted.', 'success')
    return redirect(url_for('cc_admin.draft_list'))


@bp.route('/cc-admin/loresheets/<loresheet_id>/unban', methods=['POST'])
@require_staff
def loresheet_unban(loresheet_id):
    """Lift a loresheet ban."""
    row = CcRestriction.query.filter_by(
        component_type=COMPONENT_TYPE_LORESHEET,
        component_id=loresheet_id,
    ).first()
    if row:
        db.session.delete(row)
        db.session.commit()
        flash(f'Loresheet "{loresheet_id}" unbanned.', 'success')
    return redirect(url_for('cc_admin.loresheet_list'))
