// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetRouteImport } from './routes/sheet'
import { Route as MeRouteImport } from './routes/me'
import { Route as CreateRouteImport } from './routes/create'
import { Route as PlayerNewRouteImport } from './routes/player.new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminImpersonationRouteImport } from './routes/admin.impersonation'
import { Route as StDraftDraftIdRouteImport } from './routes/st.draft.$draftId'

const SheetRoute = SheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerNewRoute = PlayerNewRouteImport.update({
  id: '/player/new',
  path: '/player/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImpersonationRoute = AdminImpersonationRouteImport.update({
  id: '/admin/impersonation',
  path: '/admin/impersonation',
  getParentRoute: () => rootRouteImport,
} as any)
const StDraftDraftIdRoute = StDraftDraftIdRouteImport.update({
  id: '/st/draft/$draftId',
  path: '/st/draft/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/player/new': typeof PlayerNewRoute
  '/me': typeof MeRoute
  '/sheet': typeof SheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/impersonation': typeof AdminImpersonationRoute
  '/st/draft/$draftId': typeof StDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/player/new': typeof PlayerNewRoute
  '/me': typeof MeRoute
  '/sheet': typeof SheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/impersonation': typeof AdminImpersonationRoute
  '/st/draft/$draftId': typeof StDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/player/new': typeof PlayerNewRoute
  '/me': typeof MeRoute
  '/sheet': typeof SheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/impersonation': typeof AdminImpersonationRoute
  '/st/draft/$draftId': typeof StDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/player/new' | '/me' | '/sheet' | '/auth/callback' | '/admin/impersonation' | '/st/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/player/new' | '/me' | '/sheet' | '/auth/callback' | '/admin/impersonation' | '/st/draft/$draftId'
  id: '__root__' | '/' | '/create' | '/player/new' | '/me' | '/sheet' | '/auth/callback' | '/admin/impersonation' | '/st/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  PlayerNewRoute: typeof PlayerNewRoute
  MeRoute: typeof MeRoute
  SheetRoute: typeof SheetRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AdminImpersonationRoute: typeof AdminImpersonationRoute
  StDraftDraftIdRoute: typeof StDraftDraftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheet': {
      id: '/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/new': {
      id: '/player/new'
      path: '/player/new'
      fullPath: '/player/new'
      preLoaderRoute: typeof PlayerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/impersonation': {
      id: '/admin/impersonation'
      path: '/admin/impersonation'
      fullPath: '/admin/impersonation'
      preLoaderRoute: typeof AdminImpersonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/st/draft/$draftId': {
      id: '/st/draft/$draftId'
      path: '/st/draft/$draftId'
      fullPath: '/st/draft/$draftId'
      preLoaderRoute: typeof StDraftDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  PlayerNewRoute: PlayerNewRoute,
  MeRoute: MeRoute,
  SheetRoute: SheetRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AdminImpersonationRoute: AdminImpersonationRoute,
  StDraftDraftIdRoute: StDraftDraftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
